config/routes.rb
Praiafit::Application.routes.draw do

  resources :messages

  resources :users, :path => "/admin/users" 
  match '/admin/users' => 'users#update', :via => :put
  match '/admin/users' => 'users#destroy', :via => :delete
  match '/admin/users/:id/messages' => 'users#messages'

  devise_for :users, :controllers => { :sessions => "sessions" } ######, :path => "/authenticate"

  match '/users/profile' => 'users#profile', :via => :put
  match '/users/whoami'  => 'users#whoami'

  match '/download/:message_id/attachment', :controller => 'attachments', :action => 'download', :constraints => { :filename =>  /[^\/]+/ } ##:constraints => { :filename => /[a-zA-Z0-9.]+/ }

end

app/models/message.rb
class Message
  include DataMapper::Resource

  property :id, Serial
  property :type, Discriminator # support for inheritance

  property :date, DateTime, :required => true, :messages => { :presence  => I18n.t("models.message.blank_date") }
  property :content, Text, :required => true, :messages => { :presence  => I18n.t("models.message.blank_content") }
  belongs_to :from, User, :required => false
  validates_presence_of :from, :message => I18n.t("models.message.blank_from")

  has n, :attachments

  def position
    pos = ""
    if from.role == :customer
      pos = "left"
    else
      pos = "right"
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_filter :authenticated_user?

  # GET /messages
  # GET /messages.json
  def index
    @messages = []
    if current_user.role == :customer
      @messages = Message.all( :from_id => current_user.id ).to_a + CoachMessage.all(:to_id => current_user.id ).to_a
    elsif current_user.role == :coach
      @messages = Message.all.to_a
    end
    @messages = @messages.sort { |m1,m2| m1.date <=> m2.date }

    respond_to do |format|
      format.html # index.html.erb
      format.json # { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.get(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    if current_user.role == :customer
      @message = Message.new(params[:message])      
    else
      @message = CoachMessage.new(params[:message])      
    end
    @message.date = Time.now
    @message.from = current_user

    respond_to do |format|
      if @message.save
        files = extract_uploaded_files(params)      
        attachments = [ ]
        files.each{ |file|
          attachment = Attachment.new
          attachment.message = @message
          attachment.filename = file.original_filename
          attachment.save_uploaded_file(file)
          attachment.save
          attachments.push(attachment)
        }
        format.html { redirect_to "/" }
        format.json { render "create", status: :created }   # { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def extract_uploaded_files(params)
    files = Array.new
    params.keys.each{ |key|
      if params[key].class.name == "ActionDispatch::Http::UploadedFile"
        files.push(params[key])
      end
    }     
    files
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.get(params[:id])

    respond_to do |format|
      if @message.update(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.get(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  

end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="control-group">
    <%= f.label :title, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :content %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :from, class: "control-label" %>
    <div class="controls">
      <%= current_user.name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :to, class: "control-label" %>
    <div class="controls">
      <%= f.select :to_id, User.all(:role.not => current_user.role ).map { |user| [ user.name, user.id ] }  %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>


<% end %>

app/views/messages/create.json.erb
{
  "from_id" : "<%= @message.from.id %>",
  "from" : "<%= @message.from.name %>", 
  <% if @message.class.name == "CoachMessage" %>
  "to" : "<%= @message.to.name %>",
  <% end %>
  "date" : "<%= @message.date.strftime("%Y/%m/%d %H:%M:%S") %>",
  "content" : "<%= @message.content %>",
  "attachments" : [ 
    <% @message.attachments.each_index{ |index| %>
      "<%= @message.attachments[index].filename %>" 
      <% if index < @message.attachments.size - 1 %>
        ,
      <% end %>
    <% } %>
  ]
}

app/views/messages/edit.html.erb
<div class="form-horizontal">

<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message, class: "btn btn-primary" %> 
<%= link_to 'Back', messages_path, class: "btn btn-primary" %>

</div>

app/views/messages/index.html.erb
<h1>Lista de Mensagens</h1>

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>From</th>
    <th>To</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.title %></td>
    <td><%= message.content %></td>
    <td><%= message.from.name %></td>
    <td><%= message.to.name %></td>
    <td><%= link_to 'Show', message, class: "btn btn-mini btn-primary" %></td>
    <td><%= link_to 'Edit', edit_message_path(message), class: "btn btn-mini btn-primary" %></td>
    <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path, class: "btn btn-primary" %>

app/views/messages/index.json.erb
[
<% @messages.each_index { |index| %>
  { 
    "from_id" : "<%= @messages[index].from.id %>",
    "from" : "<%= @messages[index].from.name %>", 
    <% if @messages[index].class.name == "Message" %>
    "to" : "treinadores",
    "to_id" : "0",
    <% else %>
    "to" : "<%= @messages[index].to.name %>",
    "to_id" : "<%= @messages[index].to.id %>",
    <% end %>
    "date" : "<%= @messages[index].date.strftime("%Y/%m/%d %H:%M:%S") %>", 
    "content" : "<%= raw StringHelper.convert_special_characters( @messages[index].content ) %>", 
    "position" : "<%= @messages[index].position %>",
    "attachments" : [ 
      <% @messages[index].attachments.each_index { |att_index| %>
        "<%= '/download/'+@messages[index].id.to_s+'/attachment?filename='+@messages[index].attachments[att_index].filename %>"
        <% if att_index < @messages[index].attachments.size - 1 %>
        ,
        <% end %>
      <% } %>
    ] 
   }
   <% if index < @messages.size - 1 %>
   , 
   <% end %>
<% } %>
]

app/views/messages/new.html.erb
<div class="form-horizontal">

<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path, class: "btn btn-primary" %>

</div>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h2><%= @message.title %></h2>
</div>

<div>
  <b>From: </b>  
  <%= @message.from.name %>
</div>

</br>

<div>
  <b>To: </b>
  <%= @message.to.name %>
</div>

</br>

<div class="well well-large">
  <%= @message.content %>
</div>

</br>

<%= link_to 'Edit', edit_message_path(@message), class: "btn btn-primary" %> |
<%= link_to 'Back', messages_path, class: "btn btn-primary" %>